version: '3.4'

services:
  rtmp:
    build: .
    image: nginx-rtmp
    network_mode: host
    volumes:
    - nginx-record:/tmp/record
  samba:
    image: dperson/samba
    network_mode: host
    environment:
      TZ: 'Asia/Shanghai'
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - nginx-record:/mnt:z
    command: '-s "record;/mnt;yes;yes;yes"'

volumes:
  nginx-record:

